image: mingc/android-build-box:latest

stages:
  - build

before_script:
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME=$(pwd)/.gradle

build_debug:
  stage: build
  script:
    - ./gradlew assembleDebug --stacktrace
  artifacts:
    paths:
      - app/build/outputs/apk/debug/*.apk
    expire_in: 1 week
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .gradle/

build_release:
  stage: build
  script:
    - ./gradlew assembleRelease --stacktrace
  artifacts:
    paths:
      - app/build/outputs/apk/release/*.apk
    expire_in: 1 week
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .gradle/
